# 图片类型
image.extensions=.jpg,.jpeg,.png,.gif,.bmp,.ico,.jfif,.webp,.svg,.tif,.tiff,.avif,.heic,.heif,.apng
# 允许在webview显示的文件类型
# allow.extensions=.jpg,.jpeg,.png,.gif,.bmp,.ico,.jfif,.webp,.svg,.tif,.tiff,.avif,.heic,.heif,.apng,.txt,.mp4
allow.extensions=.jpg,.jpeg,.png,.gif,.bmp,.ico,.jfif,.webp,.svg,.tif,.tiff,.avif,.heic,.heif,.apng,.txt,.mp4
# kkFileView地址
kkFileView_URL=https://file.kkview.cn/

# 全局代理配置（在界面中配置：NONE / SOCKS5 / HTTP）
proxy.type=NONE
proxy.host=
proxy.port=

# 默认请求头（支持用 ; 分隔，运行时会显示为多行）
# 例如：User-Agent: Mozilla/5.0;X-Forwarded-For: 127.0.0.1
request.headers=User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5410.0 Safari/537.36;Accept: */*
